{{ if (.Values.tags.autobots) and eq .Values.tags.autobots "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "transformers.fullname" . }}-autobots-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "transformers.name" . }}
data:
  transformer.mode: {{ .Values.autobots.mode }}
{{ end }}