---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: gears
 labels:
   serviceType: gears
spec:
 selector:
  matchLabels:
   serviceType: gears
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       serviceType: gears
   spec:
     containers:
     - image: localhost:32000/rwibawa/gears:1.1
       name: gears
       env:
       - name: JAVA_OPTS
         value: -Xmx64m -Xms64m
       livenessProbe:
         httpGet:
           path: /actuator/health/liveness
           port: 80
         initialDelaySeconds: 40
         timeoutSeconds: 1
         periodSeconds: 15
       readinessProbe:
         httpGet:
           path: /actuator/health
           port: 80
         initialDelaySeconds: 40
         timeoutSeconds: 1
         periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
 name: gears
spec:
 ports:
   - port: 8080
 selector:
   serviceType: gears
 clusterIP: None
